/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import utilidades.Empleado;
import utilidades.Empresa;
import utilidades.Proyecto;
import utilidades.Tarea;

/**
 *
 * @author josue
 */
public class ManejoProyecto extends javax.swing.JFrame {
    
    ArrayList<Tarea> requerimientos = new ArrayList<>();
    Proyecto proyectoActual;
    ArrayList<Empleado> responsables = new ArrayList<>();
    
    /**
     * Creates new form Reportes
     */
    public ManejoProyecto() {
        initComponents();
        setLocationRelativeTo(null);
        checkRequerimientos.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                JCheckBox cb = (JCheckBox) ae.getSource();
                if (cb.isSelected()) {
                    txtRequerimiento.setEnabled(true);
                    btnAgregar.setEnabled(true);
                } else {
                    txtRequerimiento.setEnabled(false);
                    btnAgregar.setEnabled(false);
                }
            }
        });
        btnTareaCompletada.setVisible(false);
        comboAcccion.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                switch(comboAcccion.getSelectedItem().toString()){
                    case "Asignar tarea":
                        ocultarComponentes("Asignar");
                        break;
                    case "Completar tarea":
                        ocultarComponentes("Completar");
                        break;  
                }
            }});
        setTareasJList();
        setEmpleadosList();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombreTarea = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        checkRequerimientos = new javax.swing.JCheckBox();
        txtRequerimiento = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        datePickerEntrega = new org.jdesktop.swingx.JXDatePicker();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtDias = new javax.swing.JTextField();
        txtHoras = new javax.swing.JTextField();
        btnCrear = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListTareas = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        comboAcccion = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        comboTareas = new javax.swing.JComboBox<>();
        labelResposable = new javax.swing.JLabel();
        txtResponsable = new javax.swing.JTextField();
        btnAnadirResponsable = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListEmpleados = new javax.swing.JList<>();
        btnAsignar = new javax.swing.JButton();
        btnTareaCompletada = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jPanel3 = new javax.swing.JPanel();
        costosProyecto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textCostos = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setText("Descripcion:");

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel9.setText("¿Tiene dependencias?");

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel13.setText("Duracion:");

        jButton7.setText("jButton7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("Nombre de la tarea:");

        txtNombreTarea.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtNombreTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreTareaActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setText("¿Tiene requerimientos?");

        checkRequerimientos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        checkRequerimientos.setText("Sí");
        checkRequerimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkRequerimientosActionPerformed(evt);
            }
        });

        txtRequerimiento.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtRequerimiento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRequerimientoKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel10.setText("ID del requerimiento:");

        btnAgregar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel11.setText("Fecha de entrega:");

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel12.setText("Duracion (Dias):");

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel14.setText("Horas Requeridas:");

        txtDias.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtDias.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDiasKeyTyped(evt);
            }
        });

        txtHoras.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtHoras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHorasKeyTyped(evt);
            }
        });

        btnCrear.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        jListTareas.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jScrollPane4.setViewportView(jListTareas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(datePickerEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnCrear)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtDias, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addComponent(txtNombreTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtRequerimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAgregar))
                    .addComponent(jLabel8)
                    .addComponent(checkRequerimientos))
                .addGap(52, 52, 52)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkRequerimientos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRequerimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(datePickerEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnCrear)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tareas", jPanel1);

        comboAcccion.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        comboAcccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Asignar tarea", "Completar tarea" }));

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setText("Elija una accion:");

        jLabel17.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel17.setText("Elija una tarea:");

        comboTareas.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        labelResposable.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        labelResposable.setText("<html>Añada su(s)<br>Responsable(s) por ID</html>");

        txtResponsable.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtResponsable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResponsableActionPerformed(evt);
            }
        });
        txtResponsable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtResponsableKeyTyped(evt);
            }
        });

        btnAnadirResponsable.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnAnadirResponsable.setText("Agregar");
        btnAnadirResponsable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirResponsableActionPerformed(evt);
            }
        });

        jListEmpleados.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jScrollPane2.setViewportView(jListEmpleados);

        btnAsignar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnAsignar.setText("Asignar Tarea");
        btnAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarActionPerformed(evt);
            }
        });

        btnTareaCompletada.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnTareaCompletada.setText("Marcar Tarea como completada");
        btnTareaCompletada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTareaCompletadaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(btnTareaCompletada))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(btnAnadirResponsable))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtResponsable)
                                .addComponent(comboTareas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel17)
                                .addComponent(comboAcccion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addComponent(labelResposable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(btnAsignar)
                                    .addGap(8, 8, 8))))))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboAcccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboTareas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelResposable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAnadirResponsable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAsignar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTareaCompletada)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Manejo de tareas", jPanel2);

        costosProyecto.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        costosProyecto.setText("Costos de proyecto");
        costosProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costosProyectoActionPerformed(evt);
            }
        });

        textCostos.setEditable(false);
        textCostos.setColumns(20);
        textCostos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        textCostos.setRows(5);
        jScrollPane1.setViewportView(textCostos);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(costosProyecto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(costosProyecto)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Información", jPanel3);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Proyecto: ");

        jLabel3.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel3.setText("Proyecto");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setText("Administrador:");

        jLabel5.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel5.setText("Admin");

        jLabel15.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel15.setText("Departamento:");

        jLabel16.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel16.setText("Departamento");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(65, 65, 65)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkRequerimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkRequerimientosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkRequerimientosActionPerformed

    private void txtNombreTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreTareaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreTareaActionPerformed

    private void txtResponsableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResponsableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResponsableActionPerformed

    private void btnAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarActionPerformed
        if(!responsables.isEmpty()){
            Tarea t = proyectoActual.getTarea(Integer.parseInt(comboTareas.getSelectedItem().toString()));
            for(Empleado e: responsables){
                e.addTarea(t);
            }
            txtResponsable.setText("");
            responsables.clear();
            JOptionPane.showMessageDialog(rootPane, "Tarea asignada.");
        }else{
            JOptionPane.showMessageDialog(rootPane, "No se han asignado trabajadores.");
        }
    }//GEN-LAST:event_btnAsignarActionPerformed

    private void btnTareaCompletadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTareaCompletadaActionPerformed
        Tarea t = proyectoActual.getTarea(Integer.parseInt(comboTareas.getSelectedItem().toString()));
        if(t != null){
            t.setCompleta();
        }
    }//GEN-LAST:event_btnTareaCompletadaActionPerformed

    private void setTareasJList(){
        ArrayList<Tarea> tareas = proyectoActual.getTareas();
        DefaultListModel model = new DefaultListModel();
        if(!tareas.isEmpty()){
            for(Tarea t: tareas){
                if(t.getEstado() == false){
                    model.addElement(t.getIndentificador() + " - " + t.getNombre());
                }
            }
            jListTareas.setModel(model);
        }else{
            model.addElement("No hay tareas.");
            jListTareas.setModel(model);
        }
    }
    
    private void setTareas(){
        ArrayList<Tarea> tareas = new ArrayList<>();
        for(Tarea t: proyectoActual.getTareas()){
            if(t.getEstado() == false){
                tareas.add(t);
            }
        }
        if(!tareas.isEmpty()){
            String[] arrayTareas = new String[tareas.size()];
            for(int i = 0; i < tareas.size(); i++){
                arrayTareas[i] = tareas.get(i).getNombre();
            }
            DefaultComboBoxModel model = new DefaultComboBoxModel(arrayTareas);
            comboTareas.setModel(model);
        }
    }
    
    public void setEmpleadosList(){
        ArrayList<Empleado> empleados = proyectoActual.getEmpleados();
        DefaultListModel model = new DefaultListModel();
        if(!empleados.isEmpty()){
            for(Empleado e: empleados){
                model.addElement(e.getCed() + " - " + e.getNombre());
            }
            jListEmpleados.setModel(model);
        }else{
            model.addElement("No hay Empleados");
            jListEmpleados.setModel(model);
        }
       
    }
    
    private void txtRequerimientoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRequerimientoKeyTyped
        char validar=evt.getKeyChar();
        if (Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(rootPane, "Ingresar solo numeros");
            txtRequerimiento.setText("");
        }
    }//GEN-LAST:event_txtRequerimientoKeyTyped

    private void txtDiasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiasKeyTyped
        char validar=evt.getKeyChar();
        if (Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingresar solo numeros");
            txtDias.setText("");
        }
    }//GEN-LAST:event_txtDiasKeyTyped

    private void txtHorasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHorasKeyTyped
        char validar=evt.getKeyChar();
        if (Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingresar solo numeros");
            txtHoras.setText("");
        }
    }//GEN-LAST:event_txtHorasKeyTyped

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        int id = Integer.parseInt(txtRequerimiento.getText());
        Tarea tarea = proyectoActual.getTarea(id);
        if(requerimientos.contains(tarea)){
            JOptionPane.showMessageDialog(rootPane, "Esta tarea ya esta registrada.");
        }
        if(tarea == null){
            JOptionPane.showMessageDialog(rootPane, "Esta tarea no existe.");
            txtRequerimiento.setText("");
        }else{
            requerimientos.add(tarea);
            txtRequerimiento.setText("");
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    public void ocultarComponentes(String string){
        switch(string){
            case "Asignar":
                labelResposable.setVisible(true);
                txtResponsable.setVisible(true);
                btnAnadirResponsable.setVisible(true);
                btnAsignar.setVisible(true);
                btnTareaCompletada.setVisible(false);
                break;
            case "Completar":
                labelResposable.setVisible(false);
                txtResponsable.setVisible(false);
                btnAnadirResponsable.setVisible(false);
                btnAsignar.setVisible(false);
                btnTareaCompletada.setVisible(true);
                break;  
        }
    }
    
    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        Tarea tarea = new Tarea(txtNombreTarea.getText(), datePickerEntrega.getDate(),  Double.parseDouble(txtDias.getText()),
        Double.parseDouble(txtHoras.getText()), checkRequerimientos.isSelected(), proyectoActual.getIdentificador(), proyectoActual);
        if(checkRequerimientos.isSelected()){
            tarea.setRequerimientos(requerimientos);
        }
        proyectoActual.anadirTarea(tarea);
        JOptionPane.showMessageDialog(rootPane, "Tarea registrada.");
        txtNombreTarea.setText("");
        datePickerEntrega.setDate(null);
        txtDias.setText("");
        txtHoras.setText("");
        checkRequerimientos.setSelected(false);
        txtRequerimiento.setEnabled(false);
        btnAgregar.setEnabled(false);
        txtRequerimiento.setText("");
        requerimientos.clear();
        setTareasJList();
    }//GEN-LAST:event_btnCrearActionPerformed

    private void txtResponsableKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtResponsableKeyTyped
        char validar=evt.getKeyChar();
        
        if (Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(rootPane, "Ingresar solo numeros");
            txtResponsable.setText("");
        }
    }//GEN-LAST:event_txtResponsableKeyTyped

    private void btnAnadirResponsableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirResponsableActionPerformed
        Empleado e = Empresa.getInstance().buscarEmpleado(Integer.parseInt(txtResponsable.getText()));
        if(e != null){
            responsables.add(e);
            JOptionPane.showMessageDialog(rootPane, "Responsable añadido.");
            txtResponsable.setText("");
            
        }else{
            JOptionPane.showMessageDialog(rootPane, "No existe un usuario con ese id.");
            txtResponsable.setText("");
        }
    }//GEN-LAST:event_btnAnadirResponsableActionPerformed

    private void costosProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costosProyectoActionPerformed
        ArrayList<Tarea> tareas = proyectoActual.getTareas();
        textCostos.setText("");
        for(Tarea t: tareas){
            double costo = 0;
            double horasPorPersona = (t.getHorasRequeridas() * t.getDuracion()) / t.getResponsables().size() ;
            if(!t.getResponsables().isEmpty()){
                for(Empleado e: t.getResponsables()){
                    costo += e.getSalario() * horasPorPersona;
                }
                textCostos.append(t.getNombre() + " tiene un costo de: " + costo + "\n");
            }else{
                textCostos.append("Error, esta tarea (" + t.getNombre() + ") no tiene responsables.");
            }
        }
    }//GEN-LAST:event_costosProyectoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManejoProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManejoProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManejoProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManejoProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManejoProyecto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAnadirResponsable;
    private javax.swing.JButton btnAsignar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnTareaCompletada;
    private javax.swing.JCheckBox checkRequerimientos;
    private javax.swing.JComboBox<String> comboAcccion;
    private javax.swing.JComboBox<String> comboTareas;
    private javax.swing.JButton costosProyecto;
    private org.jdesktop.swingx.JXDatePicker datePickerEntrega;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jListEmpleados;
    private javax.swing.JList<String> jListTareas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelResposable;
    private javax.swing.JTextArea textCostos;
    private javax.swing.JTextField txtDias;
    private javax.swing.JTextField txtHoras;
    private javax.swing.JTextField txtNombreTarea;
    private javax.swing.JTextField txtRequerimiento;
    private javax.swing.JTextField txtResponsable;
    // End of variables declaration//GEN-END:variables
}
